apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: kafka
    spec:
      containers:
        - image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
#          env:
#            - name: KAFKA_ADVERTISED_LISTENERS
#              value: PLAINTEXT://kafka:9094,EXTERNAL://kafka:9092
#            - name: KAFKA_INTER_BROKER_LISTENER_NAME
#              value: PLAINTEXT
#            - name: KAFKA_LISTENERS
#              value: PLAINTEXT://:9094,EXTERNAL://:9092
#            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#              value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
#            - name: KAFKA_ZOOKEEPER_CONNECT
#              value: zoo:2181

          name: kafka
          ports:
            - containerPort: 9092
              protocol: TCP
            - containerPort: 9094
              protocol: TCP
          envFrom:
            - configMapRef:
                name: kafka-config
      restartPolicy: Always
