apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: zoo
  name: zoo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zoo
  template:
    metadata:
      annotations:
        kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: zoo
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_SERVERS
              value: zoo:2888:3888
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
          image: confluentinc/cp-zookeeper:7.3.2
          imagePullPolicy: IfNotPresent
          name: zoo
          ports:
            - containerPort: 2181
              protocol: TCP
      hostname: zoo
      restartPolicy: Always
