// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: message/v1/message.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MessageService_MessageRecord_FullMethodName  = "/message.api.message.v1.MessageService/MessageRecord"
	MessageService_MessageSend_FullMethodName    = "/message.api.message.v1.MessageService/MessageSend"
	MessageService_GetNewMessages_FullMethodName = "/message.api.message.v1.MessageService/GetNewMessages"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	MessageRecord(ctx context.Context, in *DouyinMessageRecordRequest, opts ...grpc.CallOption) (*DouyinMessageRecordResponse, error)
	MessageSend(ctx context.Context, in *DouyinMessageSendRequest, opts ...grpc.CallOption) (*DouyinMessageSendResponse, error)
	//  string message = 2; // 和该好友的最新聊天消息
	//  int64 msgType = 3; // message消息的类型，0 => 当前请求用户接收的消息， 1 => 当前请求用户发送的消息
	//获得用户和每个好友的最新一条消息
	GetNewMessages(ctx context.Context, in *GetNewMessagesRequest, opts ...grpc.CallOption) (*GetNewMessagesResponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) MessageRecord(ctx context.Context, in *DouyinMessageRecordRequest, opts ...grpc.CallOption) (*DouyinMessageRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DouyinMessageRecordResponse)
	err := c.cc.Invoke(ctx, MessageService_MessageRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MessageSend(ctx context.Context, in *DouyinMessageSendRequest, opts ...grpc.CallOption) (*DouyinMessageSendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DouyinMessageSendResponse)
	err := c.cc.Invoke(ctx, MessageService_MessageSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) GetNewMessages(ctx context.Context, in *GetNewMessagesRequest, opts ...grpc.CallOption) (*GetNewMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewMessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_GetNewMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	MessageRecord(context.Context, *DouyinMessageRecordRequest) (*DouyinMessageRecordResponse, error)
	MessageSend(context.Context, *DouyinMessageSendRequest) (*DouyinMessageSendResponse, error)
	//  string message = 2; // 和该好友的最新聊天消息
	//  int64 msgType = 3; // message消息的类型，0 => 当前请求用户接收的消息， 1 => 当前请求用户发送的消息
	//获得用户和每个好友的最新一条消息
	GetNewMessages(context.Context, *GetNewMessagesRequest) (*GetNewMessagesResponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) MessageRecord(context.Context, *DouyinMessageRecordRequest) (*DouyinMessageRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageRecord not implemented")
}
func (UnimplementedMessageServiceServer) MessageSend(context.Context, *DouyinMessageSendRequest) (*DouyinMessageSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageSend not implemented")
}
func (UnimplementedMessageServiceServer) GetNewMessages(context.Context, *GetNewMessagesRequest) (*GetNewMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewMessages not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_MessageRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinMessageRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MessageRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MessageRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MessageRecord(ctx, req.(*DouyinMessageRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MessageSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinMessageSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MessageSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MessageSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MessageSend(ctx, req.(*DouyinMessageSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetNewMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).GetNewMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_GetNewMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).GetNewMessages(ctx, req.(*GetNewMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.api.message.v1.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MessageRecord",
			Handler:    _MessageService_MessageRecord_Handler,
		},
		{
			MethodName: "MessageSend",
			Handler:    _MessageService_MessageSend_Handler,
		},
		{
			MethodName: "GetNewMessages",
			Handler:    _MessageService_GetNewMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/v1/message.proto",
}
