apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: apisix
  name: apisix
spec:
  ports:
  - name: "9180"
    port: 9180
    targetPort: 9180
  - name: "9080"
    port: 9080
    targetPort: 9080
  - name: "9091"
    port: 9091
    targetPort: 9091
  - name: "9443"
    port: 9443
    targetPort: 9443
  - name: "7092"
    port: 7092
    targetPort: 9092
  - name: "7777"
    port: 7777
    targetPort: 80
  - name: "9333"
    port: 9333
    targetPort: 8080
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: apisix
status:
  loadBalancer: {}
