apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: etcd-node3
  name: etcd-node3
spec:
  ports:
  - name: "2579"
    port: 2579
    targetPort: 2379
  - name: "2580"
    port: 2580
    targetPort: 2380
  selector:
    io.kompose.service: etcd-node3
status:
  loadBalancer: {}
