apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: etcd-node
  name: etcd-node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etcd-node
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: etcd-node
    spec:
      containers:
      - env:
        - name: ALLOW_NONE_AUTHENTICATION
          value: yes
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://etcd-node:2379
        - name: ETCD_DATA_DIR
          value: /etcd-data
        - name: ETCD_ENABLE_V2
          value: "true"
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: http://etcd-node:2380
        - name: ETCD_INITIAL_CLUSTER
          value: etcd-node=http://etcd-node:2380,etcd-node2=http://etcd-node2:2380,etcd-node3=http://etcd-node3:2380
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: new
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: etcd-cluster
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_LISTEN_PEER_URLS
          value: http://0.0.0.0:2380
        - name: ETCD_NAME
          value: etcd-node
        image: quay.io/coreos/etcd:v3.5.0
        imagePullPolicy: ""
        name: etcd-node
        ports:
        - containerPort: 2379
        - containerPort: 2380
        resources: {}
        volumeMounts:
        - mountPath: /etcd-data
          name: etcd-node-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: etcd-node-claim0
        persistentVolumeClaim:
          claimName: etcd-node-claim0
status: {}
