apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: jaeger
    spec:
      containers:
      - image: jaegertracing/all-in-one:latest
        imagePullPolicy: ""
        name: jaeger
        ports:
        - containerPort: 16686
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 14268
        - containerPort: 14250
        - containerPort: 9411
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
