apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - env:
        - name: LS_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
        - name: MONITORING_ENABLED
          value: "false"
        - name: TZ
          value: Asia/Shanghai
        image: logstash:8.6.0
        imagePullPolicy: ""
        name: logstash
        ports:
        - containerPort: 5044
        - containerPort: 50000
        - containerPort: 9600
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline/logstash.conf
          name: logstash-claim0
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: logstash-claim1
        - mountPath: /home/public/
          name: logstash-claim2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: logstash-claim0
        persistentVolumeClaim:
          claimName: logstash-claim0
      - name: logstash-claim1
        persistentVolumeClaim:
          claimName: logstash-claim1
      - name: logstash-claim2
        persistentVolumeClaim:
          claimName: logstash-claim2
status: {}
