apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nacos
  name: nacos
spec:
  ports:
  - name: "8848"
    port: 8848
    targetPort: 8848
  - name: "9848"
    port: 9848
    targetPort: 9848
  - name: "9849"
    port: 9849
    targetPort: 9849
  selector:
    io.kompose.service: nacos
status:
  loadBalancer: {}
