source:
   type: mysql
   name: Comment MySQL Source
   scan.startup.mode: latest-offset
   hostname: 127.0.0.1
   port: 7500
   username: root
   password: 123456
   tables: comment.\.*
#  user.user
   server-id: 5404


sink:
  type: kafka
  name: Comment-Kafka-Sink
  topic: comment-redis
  properties.bootstrap.servers:  EXTERNAL://127.0.0.1:9092


pipeline:
  name: Comment MySQL to Kafka Pipeline
  parallelism: 1


