source:
  type: mysql
  name: Favorite MySQL Source
  scan.startup.mode: latest-offset
  hostname: 127.0.0.1
  port: 7500
  username: root
  password: 123456
  tables: favorite.\.*
  server-id: 5403


sink:
  type: kafka
  name: Favorite-Kafka-Sink
  topic: favorite-redis
  properties.bootstrap.servers:  EXTERNAL://127.0.0.1:9092


pipeline:
  name: Favorite MySQL to Kafka Pipeline
  parallelism: 1


