source:
   type: mysql
   name: Message MySQL Source
   scan.startup.mode: latest-offset
   hostname: 127.0.0.1
   port: 7500
   username: root
   password: 123456
   tables: message.\.*
#  user.user
   server-id: 5406


sink:
  type: kafka
  name: Message-Kafka-Sink
  topic: message-redis
  properties.bootstrap.servers:  EXTERNAL://127.0.0.1:9092


pipeline:
  name: Message MySQL to Kafka Pipeline
  parallelism: 1


