source:
   type: mysql
   name: User MySQL Source
   scan.startup.mode: latest-offset
   hostname: 127.0.0.1
   port: 7500
   username: root
   password: 123456
   tables: user.\.*
#  user.user
   server-id: 5401


sink:
  type: kafka
  name: User-Kafka-Sink
  topic: user-redis
  properties.bootstrap.servers:  EXTERNAL://127.0.0.1:9092


pipeline:
  name: User MySQL to Kafka Pipeline
  parallelism: 1


