// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"comment/internal/biz"
	"comment/internal/conf"
	"comment/internal/data"
	"comment/internal/pkg/ckafka"
	"comment/internal/server"
	"comment/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(prometheus *conf.Prometheus, kafka *conf.Kafka, etcd *conf.Etcd, auth *conf.Auth, confServer *conf.Server, confService *conf.Service, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	registrar, cleanup, err := data.NewRegistrar(etcd, logger)
	if err != nil {
		return nil, nil, err
	}
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	discovery := data.NewDiscovery(etcd)
	favoriteServiceClient := data.NewFavoriteClient(discovery, confService)
	userServiceClient := data.NewUserServiceClient(discovery, confService)
	relationServiceClient := data.NewRelationClient(discovery, confService)
	videoServiceClient := data.NewVideoClient(discovery, confService)
	reader := ckafka.InitKafkaConsumer(logger, kafka, client)
	dataData, cleanup2, err := data.NewData(logger, db, client, favoriteServiceClient, userServiceClient, relationServiceClient, videoServiceClient, reader)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	commentRepo := data.NewCommentRepo(dataData, logger)
	commentUsecase := biz.NewCommentUsecase(commentRepo, logger)
	commentService := service.NewCommentService(commentUsecase, auth, logger)
	grpcServer := server.NewGRPCServer(prometheus, confServer, auth, commentService, logger)
	app := newApp(registrar, logger, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
