apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: etcd-node3
  name: etcd-node3
spec:
  ports:
    - name: "2579"
      port: 2579
      targetPort: 2379
    - name: "2580"
      port: 2580
      targetPort: 2380
  selector:
    io.kompose.service: etcd-node3
