apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: etcd-node
  name: etcd-node
spec:
  ports:
    - name: "2379"
      port: 2379
      targetPort: 2379
    - name: "2380"
      port: 2380
      targetPort: 2380
  selector:
    io.kompose.service: etcd-node
