apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: favorite
  name: favorite
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 8003
    - name: "8883"
      port: 8883
      targetPort: 8883
  selector:
    io.kompose.service: favorite
