apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  ports:
    - name: "11111"
      port: 11111
      targetPort: 8080
    - name: "11112"
      port: 11112
      targetPort: 50000
  selector:
    io.kompose.service: jenkins
