apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: message
  name: message
spec:
  ports:
    - name: "8006"
      port: 8006
      targetPort: 8006
    - name: "8886"
      port: 8886
      targetPort: 8886
  selector:
    io.kompose.service: message
