apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_general_ci
            - --explicit_defaults_for_timestamp=true
            - --lower_case_table_names=1
            - --log-bin=mysql-bin
            - --binlog-format=ROW
            - --server-id=1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: TZ
              value: Asia/Shanghai
#            - name: MYSQL_DATABASE
#              value: user
#            - name: MYSQL_DATABASE
#              value: video
#            - name: MYSQL_DATABASE
#              value: comment
#            - name: MYSQL_DATABASE
#              value: message
#            - name: MYSQL_DATABASE
#              value: favorite
          image: mysql:8.0.20
          imagePullPolicy: IfNotPresent
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: config
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: mysql-init
