apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: nacos
  name: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nacos
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: nacos
    spec:
      containers:
        - env:
            - name: MODE
              value: standalone
          image: nacos/nacos-server:latest
          imagePullPolicy: IfNotPresent
          name: nacos
          ports:
            - containerPort: 8848
              protocol: TCP
            - containerPort: 9848
              protocol: TCP
            - containerPort: 9849
              protocol: TCP
          volumeMounts:
            - mountPath: /home/nacos/logs
              name: nacos-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/lanmengyou/code/go_code/TikTok/deply/nacos/logs
          name: nacos-hostpath0
