apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: relation
  name: relation
spec:
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8005
    - name: "8885"
      port: 8885
      targetPort: 8885
  selector:
    io.kompose.service: relation
