apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: user
  name: user
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: "8881"
      port: 8881
      targetPort: 8881
  selector:
    io.kompose.service: user
