apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: video
  name: video
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8002
    - name: "8882"
      port: 8882
      targetPort: 8882
  selector:
    io.kompose.service: video
