apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: video
  name: video
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: video
  template:
    metadata:
      annotations:
        kompose.cmd: /home/lanmengyou/code/go_code/kompose/kompose convert -f docker-compose.yml --volumes hostPath -o ./k8s
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: video
    spec:
      containers:
        - image: lanmengyou/tiktok-video:v1.0.0
          imagePullPolicy: IfNotPresent
          name: video
          ports:
            - containerPort: 8002
              protocol: TCP
            - containerPort: 8882
              protocol: TCP
      restartPolicy: Always
