CREATE DATABASE IF NOT EXISTS video;

CREATE DATABASE IF NOT EXISTS favorite;

CREATE DATABASE IF NOT EXISTS user;

CREATE DATABASE IF NOT EXISTS message;

CREATE DATABASE IF NOT EXISTS comment;

CREATE DATABASE IF NOT EXISTS relation;

CREATE DATABASE IF NOT EXISTS nacos_config;