source:
  type: mysql
  name: MySQL Source
  scan.startup.mode: latest-offset
  hostname: mysql
  port: 7500
  username: root
  password: 123456
  tables: video.\.*
  #  user.user
  server-id: 5402


sink:
  type: kafka
  name: Kafka Sink
  topic: video-redis
  properties.bootstrap.servers:  EXTERNAL://kafka:9092


pipeline:
  name: Video MySQL to Kafka Pipeline
  parallelism: 2


