server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8885
    timeout: 1s

service:
  user:
    endpoint: discovery:///TikTok.user.service
  favorite:
    endpoint: discovery:///TikTok.favorite.service
  video:
    endpoint: discovery:///TikTok.video.service
  comment:
    endpoint: discovery:///TikTok.comment.service
  relation:
    endpoint: discovery:///TikTok.relation.service
  message:
    endpoint: discovery:///TikTok.message.service

data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:7500)/video?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:
  endpoint: http://127.0.0.1:14268/api/traces

auth:
  jwt_key:

etcd:
  address: 127.0.0.1:2379

prometheus:
  addr: :7272
  path: /metrics

kafka:
  broker: 127.0.0.1:9092
  log:
    topic: TikTok-log
    groupId: TikTok-log
  video:
    video:  #video服务的video数据库
      topic: video-redis
      groupId: video-redis
  user:
    user:
      topic: user-redis
      groupId: user-redis
  comment:
    comment:
      topic: comment-redis
      groupId: comment-redis
  favorite:
    favorite:
      topic: favorite-redis
      groupId: favorite-redis
  relation:
    relation:
      topic: relation-redis
      groupId: relation-redis
  message:
    message:
      topic: message-redis
      groupId: message-redis


aliyunOSS:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:
